language: csharp
solution: MutagenRuntime.sln
install:
  - nuget restore MutagenRuntime.sln
  - sudo apt-get install nunit-console
script:
  - xbuild /p:Configuration=Release MutagenRuntime.sln
after_script:
  - nunit-console  ./MutagenRuntime.Test/bin/Release/MutagenRuntime.Test.dll
  - nunit-console  ./MutagenRuntime.LuaFrontEnd.Test/bin/Release/Mutagen.LuaFrontend.Test.dll
