language: csharp
solution: mutagen.sln
install:
  - nuget restore mutagen.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release mutagen.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./MTest/bin/Release/MTest.dll